### ISSUE TITLE
Projects without trademarks

### ISSUE THREAD

**Issue by iamwillbar** [github/MVG#24]
If a project doesn't have trademarks (yet), should we just exclude `TRADEMARKS.md` and references to it?

cc @royaljust

**Comment by royaljust** [comment]
No, it should be kept. At least in the United States, even if your trademark is unregistered you develop some rights in the name you use to provide goods and services. Here's a resource on the topic: https://www.legalzoom.com/articles/what-are-common-law-trademark-rights 

So just using the name somewhere accumulates some rights, so its worth giving people guidance on how they can and cannot use your project's name.
